<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>KoalaNotes</AssemblyName>
    <RootNamespace>KoalaNotes</RootNamespace>
    <NoWarn>8600;8602</NoWarn>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <ApplicationIcon>Assets\koala.ico</ApplicationIcon>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.3" />
    <PackageReference Include="Mapsui.Avalonia" Version="4.1.8" />
    <None Remove="Assets\koala.ico" />
    <AvaloniaResource Include="Assets\koala.ico" />
    <AvaloniaResource Include="Assets\gtfobins.json"/>
  </ItemGroup>
</Project>